### ISSUE TITLE
Blocking operation restriction for Reactor Netty threads

### ISSUE THREAD

**Issue by cmario** [spring-projects/spring-session-data-mongodb#43]
Hello,

in version 0.7.6 of reactor-netty they added a restriction for blocking Reactor Netty threads that causes in my application the following exception:

```
java.lang.IllegalStateException: block()/blockFirst()/blockLast() are blocking, which is not supported in thread reactor-http-client-epoll-8
	at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:77) ~[reactor-core-3.1.9.RELEASE.jar!/:3.1.9.RELEASE]
	at reactor.core.publisher.Mono.block(Mono.java:1183) ~[reactor-core-3.1.9.RELEASE.jar!/:3.1.9.RELEASE]
	at org.springframework.data.mongodb.core.index.IndexOperationsAdapter$1.ensureIndex(IndexOperationsAdapter.java:45) ~[spring-data-mongodb-2.0.10.RELEASE.jar!/:2.0.10.RELEASE]
	at org.springframework.data.mongodb.core.index.MongoPersistentEntityIndexCreator.createIndex(MongoPersistentEntityIndexCreator.java:145) ~[spring-data-mongodb-2.0.10.RELEASE.jar!/:2.0.10.RELEASE]
	at org.springframework.data.mongodb.core.index.MongoPersistentEntityIndexCreator.checkForAndCreateIndexes(MongoPersistentEntityIndexCreator.java:135) ~[spring-data-mongodb-2.0.10.RELEASE.jar!/:2.0.10.RELEASE]
	at org.springframework.data.mongodb.core.index.MongoPersistentEntityIndexCreator.checkForIndexes(MongoPersistentEntityIndexCreator.java:127) ~[spring-data-mongodb-2.0.10.RELEASE.jar!/:2.0.10.RELEASE]
	at org.springframework.data.mongodb.core.index.MongoPersistentEntityIndexCreator.onApplicationEvent(MongoPersistentEntityIndexCreator.java:111) ~[spring-data-mongodb-2.0.10.RELEASE.jar!/:2.0.10.RELEASE]
	at org.springframework.data.mongodb.core.index.MongoPersistentEntityIndexCreator.onApplicationEvent(MongoPersistentEntityIndexCreator.java:54) ~[spring-data-mongodb-2.0.10.RELEASE.jar!/:2.0.10.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172) ~[spring-context-5.0.9.RELEASE.jar!/:5.0.9.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165) ~[spring-context-5.0.9.RELEASE.jar!/:5.0.9.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) ~[spring-context-5.0.9.RELEASE.jar!/:5.0.9.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:400) ~[spring-context-5.0.9.RELEASE.jar!/:5.0.9.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:354) ~[spring-context-5.0.9.RELEASE.jar!/:5.0.9.RELEASE]
	at org.springframework.data.mapping.context.AbstractMappingContext.addPersistentEntity(AbstractMappingContext.java:420) ~[spring-data-commons-2.0.10.RELEASE.jar!/:2.0.10.RELEASE]
	at org.springframework.data.mapping.context.AbstractMappingContext.getPersistentEntity(AbstractMappingContext.java:229) ~[spring-data-commons-2.0.10.RELEASE.jar!/:2.0.10.RELEASE]
	at org.springframework.data.mapping.context.AbstractMappingContext.getPersistentEntity(AbstractMappingContext.java:172) ~[spring-data-commons-2.0.10.RELEASE.jar!/:2.0.10.RELEASE]
	at org.springframework.data.mapping.context.AbstractMappingContext.getPersistentEntity(AbstractMappingContext.java:85) ~[spring-data-commons-2.0.10.RELEASE.jar!/:2.0.10.RELEASE]
	at org.springframework.data.mapping.context.MappingContext.getRequiredPersistentEntity(MappingContext.java:70) ~[spring-data-commons-2.0.10.RELEASE.jar!/:2.0.10.RELEASE]
	at org.springframework.data.mongodb.core.ReactiveMongoTemplate.determineCollectionName(ReactiveMongoTemplate.java:2247) ~[spring-data-mongodb-2.0.10.RELEASE.jar!/:2.0.10.RELEASE]
	at org.springframework.data.mongodb.core.ReactiveMongoTemplate.findOne(ReactiveMongoTemplate.java:579) ~[spring-data-mongodb-2.0.10.RELEASE.jar!/:2.0.10.RELEASE]
	...
```

I am using spring-boot version 2.0.5.RELEASE that comes with the following dependencies:

- Spring mongodb 2.0.10
- Reactor netty 0.7.9
- Reactor core 3.1.9

Regards
Mario

**Comment by cmario** [comment]
Please ignore the issue, I thought I was in the spring-data-mongodb project.
