### ISSUE TITLE
java.lang.ClassCastException: org.springframework.session.data.mongo.MongoSession cannot be cast to org.springframework.session.ExpiringSession

### ISSUE THREAD

**Issue by activey** [spring-projects/spring-session-data-mongodb#94]
Hi,

I'm using spring-session-core in version 2.2.0.M1 and spring-session-data-mongodb in version 2.2.0.M2, after trying to create new session I'm getting the following exception:

```
java.lang.ClassCastException: org.springframework.session.data.mongo.MongoSession cannot be cast to org.springframework.session.ExpiringSession
	at org.springframework.session.web.http.SessionRepositoryFilter$SessionRepositoryRequestWrapper.getSession(SessionRepositoryFilter.java:372) ~[spring-session-2.0.0.M1.jar:na]
	at org.springframework.session.web.http.SessionRepositoryFilter$SessionRepositoryRequestWrapper.getSession(SessionRepositoryFilter.java:217) ~[spring-session-2.0.0.M1.jar:na]
	at javax.servlet.http.HttpServletRequestWrapper.getSession(HttpServletRequestWrapper.java:241) ~[tomcat-embed-core-9.0.16.jar:9.0.16]
	at javax.servlet.http.HttpServletRequestWrapper.getSession(HttpServletRequestWrapper.java:241) ~[tomcat-embed-core-9.0.16.jar:9.0.16]
	at javax.servlet.http.HttpServletRequestWrapper.getSession(HttpServletRequestWrapper.java:241) ~[tomcat-embed-core-9.0.16.jar:9.0.16]
```
What can I do about it?

Many thanks in advance for any response.

**Comment by activey** [comment]
Nevermind, my bad, was using wrong artifact ;P

**Comment by gregturn** [comment]
For record purposes, `ExpiringSession` was merged into `Session` [in 2017](https://github.com/spring-projects/spring-session/commit/4cf26d9c361f3f5d70dbf06dbb0826f8d2735f31).

**Comment by Bharathi9698** [comment]
@activey Which version of spring session did you use? I am facing same issue. 
I am using spring-session:2.0.0.M1 , spring-session-data-mongodb : 2.4.2
